name = "monkey-barrel"
main = "worker/index.js"
compatibility_date = "2024-12-01"

[assets]
directory = ".svelte-kit/cloudflare"
binding = "ASSETS"

[durable_objects]
bindings = [
  { name = "IMPOSTOR_ROOM", class_name = "ImpostorRoom" },
  { name = "PRESIDENT_ROOM", class_name = "PresidentRoom" },
  { name = "CHASE_QUEEN_ROOM", class_name = "ChaseTheQueenRoom" }
]

[[migrations]]
tag = "v1"
new_classes = ["ImpostorRoom"]

[[migrations]]
tag = "v2"
new_classes = ["PresidentRoom"]

[[migrations]]
tag = "v3"
new_classes = ["ChaseTheQueenRoom"]

[[d1_databases]]
binding = "DB"
database_name = "monkey-barrel-db"
database_id = "local"

[vars]
ENVIRONMENT = "production"
