export interface SpectrumCard {
	left: string;
	right: string;
	category: string;
}

export const CATEGORY_LABELS: Record<string, string> = {
	opinions: 'Opinions',
	physical: 'Physical',
	abstract: 'Abstract',
	pop_culture: 'Pop Culture',
	food: 'Food & Drink',
	social: 'Social',
	absurd: 'Absurd',
	friend_group: 'Friend Group',
	technology: 'Technology',
	lifestyle: 'Lifestyle',
};

const deck: SpectrumCard[] = [
	// opinions
	{ left: 'Overrated', right: 'Underrated', category: 'opinions' },
	{ left: 'Guilty Pleasure', right: 'Genuinely Great', category: 'opinions' },
	{ left: 'Overhyped', right: 'Underhyped', category: 'opinions' },
	{ left: 'Terrible Gift', right: 'Perfect Gift', category: 'opinions' },
	{ left: 'Waste of Time', right: 'Worth Every Minute', category: 'opinions' },
	{ left: 'Skip It', right: 'Must Experience', category: 'opinions' },
	{ left: 'Overpriced', right: 'Bargain', category: 'opinions' },
	{ left: 'Deeply Cringe', right: 'Totally Cool', category: 'opinions' },
	{ left: 'Boring', right: 'Thrilling', category: 'opinions' },
	{ left: 'Too Basic', right: 'Too Niche', category: 'opinions' },
	{ left: 'Peak Nostalgia', right: 'Better Now', category: 'opinions' },
	{ left: 'Should Be Illegal', right: 'Should Be Required', category: 'opinions' },
	{ left: 'Bad First Impression', right: 'Great First Impression', category: 'opinions' },
	{ left: 'Kids Only', right: 'Adults Only', category: 'opinions' },
	{ left: 'Cancelled Correctly', right: 'Cancelled Unfairly', category: 'opinions' },
	{ left: 'Overstayed Welcome', right: 'Gone Too Soon', category: 'opinions' },
	{ left: 'Underachieved', right: 'Overachieved', category: 'opinions' },
	{ left: 'Secretly Terrible', right: 'Secretly Amazing', category: 'opinions' },
	{ left: 'Try Once', right: 'Do Every Day', category: 'opinions' },
	{ left: 'Better Alone', right: 'Better With Others', category: 'opinions' },
	{ left: 'Total Scam', right: 'Worth the Price', category: 'opinions' },
	{ left: 'Peaked Already', right: 'Still Getting Better', category: 'opinions' },
	{ left: 'Needs a Rebrand', right: 'Perfect As Is', category: 'opinions' },
	{ left: 'Only in Theory', right: 'Works in Practice', category: 'opinions' },
	{ left: 'Dying Trend', right: 'Here to Stay', category: 'opinions' },
	{ left: 'Needs More Hype', right: 'Needs Less Hype', category: 'opinions' },
	{ left: 'Forgettable', right: 'Unforgettable', category: 'opinions' },
	{ left: 'Guilty Pleasure', right: 'No Guilt About It', category: 'opinions' },
	{ left: 'Worse Than You Think', right: 'Better Than You Think', category: 'opinions' },
	{ left: 'Concept Is Better', right: 'Execution Is Better', category: 'opinions' },

	// physical
	{ left: 'Hot', right: 'Cold', category: 'physical' },
	{ left: 'Soft', right: 'Hard', category: 'physical' },
	{ left: 'Fast', right: 'Slow', category: 'physical' },
	{ left: 'Loud', right: 'Quiet', category: 'physical' },
	{ left: 'Tiny', right: 'Enormous', category: 'physical' },
	{ left: 'Rough', right: 'Smooth', category: 'physical' },
	{ left: 'Light', right: 'Heavy', category: 'physical' },
	{ left: 'Sharp', right: 'Dull', category: 'physical' },
	{ left: 'Wet', right: 'Dry', category: 'physical' },
	{ left: 'Bright', right: 'Dark', category: 'physical' },
	{ left: 'Flexible', right: 'Rigid', category: 'physical' },
	{ left: 'Fragile', right: 'Indestructible', category: 'physical' },
	{ left: 'Freezing Cold', right: 'Scorching Hot', category: 'physical' },
	{ left: 'Microscopic', right: 'Massive', category: 'physical' },
	{ left: 'Feather Light', right: 'Crushing Heavy', category: 'physical' },
	{ left: 'Dead Silent', right: 'Deafening', category: 'physical' },
	{ left: 'Paper Thin', right: 'Solid Rock', category: 'physical' },
	{ left: 'Glacially Slow', right: 'Lightning Fast', category: 'physical' },
	{ left: 'Transparent', right: 'Opaque', category: 'physical' },
	{ left: 'Sticky', right: 'Slippery', category: 'physical' },
	{ left: 'Hollow', right: 'Solid', category: 'physical' },
	{ left: 'Elastic', right: 'Brittle', category: 'physical' },
	{ left: 'Flat', right: 'Spiky', category: 'physical' },
	{ left: 'Odorless', right: 'Pungent', category: 'physical' },
	{ left: 'Compact', right: 'Sprawling', category: 'physical' },
	{ left: 'Shallow', right: 'Deep', category: 'physical' },
	{ left: 'Narrow', right: 'Wide', category: 'physical' },
	{ left: 'Dusty', right: 'Polished', category: 'physical' },
	{ left: 'Flimsy', right: 'Sturdy', category: 'physical' },

	// abstract
	{ left: 'Bad Superpower', right: 'Great Superpower', category: 'abstract' },
	{ left: 'Unethical', right: 'Ethical', category: 'abstract' },
	{ left: 'Simple', right: 'Complex', category: 'abstract' },
	{ left: 'Chaotic', right: 'Orderly', category: 'abstract' },
	{ left: 'Selfish', right: 'Selfless', category: 'abstract' },
	{ left: 'Short-Term Thinking', right: 'Long-Term Thinking', category: 'abstract' },
	{ left: 'Impractical', right: 'Practical', category: 'abstract' },
	{ left: 'Risky', right: 'Safe', category: 'abstract' },
	{ left: 'Overconfident', right: 'Underconfident', category: 'abstract' },
	{ left: 'Too Honest', right: 'Too Diplomatic', category: 'abstract' },
	{ left: 'Weak Argument', right: 'Compelling Argument', category: 'abstract' },
	{ left: 'Backwards Thinking', right: 'Forward Thinking', category: 'abstract' },
	{ left: 'Bad Omen', right: 'Good Omen', category: 'abstract' },
	{ left: 'Cursed Ability', right: 'Blessed Ability', category: 'abstract' },
	{ left: 'Luck-Based', right: 'Skill-Based', category: 'abstract' },
	{ left: 'Reactive', right: 'Proactive', category: 'abstract' },
	{ left: 'Nature', right: 'Nurture', category: 'abstract' },
	{ left: 'Ancient Wisdom', right: 'Modern Logic', category: 'abstract' },
	{ left: 'Easily Faked', right: 'Impossible to Fake', category: 'abstract' },
	{ left: 'Means Nothing', right: 'Means Everything', category: 'abstract' },
	{ left: 'Temporary', right: 'Permanent', category: 'abstract' },
	{ left: 'Instinct', right: 'Calculated', category: 'abstract' },
	{ left: 'Meaningless', right: 'Life-Changing', category: 'abstract' },
	{ left: 'Freedom', right: 'Security', category: 'abstract' },
	{ left: 'Quantity', right: 'Quality', category: 'abstract' },
	{ left: 'Head Decision', right: 'Heart Decision', category: 'abstract' },
	{ left: 'Gentle Power', right: 'Brute Force', category: 'abstract' },
	{ left: 'Taught', right: 'Self-Discovered', category: 'abstract' },
	{ left: 'Predictable', right: 'Unpredictable', category: 'abstract' },

	// pop_culture
	{ left: 'One-Hit Wonder', right: 'Legend', category: 'pop_culture' },
	{ left: 'Mainstream', right: 'Underground', category: 'pop_culture' },
	{ left: 'Classic', right: 'Modern', category: 'pop_culture' },
	{ left: 'Opening Act', right: 'Headliner', category: 'pop_culture' },
	{ left: 'Cult Favorite', right: 'Massive Hit', category: 'pop_culture' },
	{ left: 'First Season Peak', right: 'Better Each Season', category: 'pop_culture' },
	{ left: 'Style Over Substance', right: 'Substance Over Style', category: 'pop_culture' },
	{ left: 'Reboot Ruined It', right: 'Reboot Saved It', category: 'pop_culture' },
	{ left: 'Fandom Is Toxic', right: 'Fandom Is Great', category: 'pop_culture' },
	{ left: 'Aged Badly', right: 'Aged Perfectly', category: 'pop_culture' },
	{ left: 'Box Office Bomb', right: 'Box Office Smash', category: 'pop_culture' },
	{ left: 'Forgotten', right: 'Timeless', category: 'pop_culture' },
	{ left: 'Before Its Time', right: 'Of Its Time', category: 'pop_culture' },
	{ left: 'Sequel Ruined It', right: 'Sequel Improved It', category: 'pop_culture' },
	{ left: 'Award Bait', right: 'Award Deserving', category: 'pop_culture' },
	{ left: 'Nostalgia Bait', right: 'Genuinely Iconic', category: 'pop_culture' },
	{ left: 'Meme-ified', right: 'Still Respected', category: 'pop_culture' },
	{ left: 'Niche Appeal', right: 'Universal Appeal', category: 'pop_culture' },
	{ left: 'Carried by Soundtrack', right: 'Carried by Plot', category: 'pop_culture' },
	{ left: 'Better as a Book', right: 'Better as a Movie', category: 'pop_culture' },
	{ left: 'Typecast Forever', right: 'Incredible Range', category: 'pop_culture' },
	{ left: 'Peak Was the Trailer', right: 'Better Than the Trailer', category: 'pop_culture' },
	{ left: 'Binge Watch', right: 'Weekly Release', category: 'pop_culture' },
	{ left: 'Overpowered Character', right: 'Underpowered Character', category: 'pop_culture' },
	{ left: 'Sold Out', right: 'Stayed True', category: 'pop_culture' },
	{ left: 'Cancelled Too Early', right: 'Ended Perfectly', category: 'pop_culture' },
	{ left: 'Cringe Dialogue', right: 'Quotable Lines', category: 'pop_culture' },
	{ left: 'Background Music', right: 'Full Attention Music', category: 'pop_culture' },
	{ left: 'Fan Service', right: 'Bold Choice', category: 'pop_culture' },

	// food
	{ left: 'Healthy', right: 'Unhealthy', category: 'food' },
	{ left: 'Comfort Food', right: 'Fancy Food', category: 'food' },
	{ left: 'Sweet', right: 'Savory', category: 'food' },
	{ left: 'Breakfast Only', right: 'Anytime Food', category: 'food' },
	{ left: 'Acquired Taste', right: 'Universally Loved', category: 'food' },
	{ left: 'Solo Meal', right: 'Share With Everyone', category: 'food' },
	{ left: 'Party Food', right: 'Romantic Dinner', category: 'food' },
	{ left: 'Plain', right: 'Bold Flavor', category: 'food' },
	{ left: 'Cheap Eats', right: 'Splurge Worthy', category: 'food' },
	{ left: 'Smells Terrible', right: 'Smells Amazing', category: 'food' },
	{ left: 'Looks Terrible', right: 'Looks Beautiful', category: 'food' },
	{ left: 'Takes Forever', right: 'Ready Instantly', category: 'food' },
	{ left: 'Kids Hate It', right: 'Kids Love It', category: 'food' },
	{ left: 'Finger Food', right: 'Fork and Knife', category: 'food' },
	{ left: 'Midnight Snack', right: 'Sunday Brunch', category: 'food' },
	{ left: 'Divisive', right: 'Crowd Pleaser', category: 'food' },
	{ left: 'Fuel', right: 'Experience', category: 'food' },
	{ left: 'Hot Dish', right: 'Cold Dish', category: 'food' },
	{ left: 'Eat the Leftovers', right: 'Throw It Out', category: 'food' },
	{ left: 'Dip Required', right: 'Perfect Plain', category: 'food' },
	{ left: 'Gas Station Quality', right: 'Restaurant Quality', category: 'food' },
	{ left: 'Better Homemade', right: 'Better Store-Bought', category: 'food' },
	{ left: 'Drink It Warm', right: 'Drink It Ice Cold', category: 'food' },
	{ left: 'Meal Replacement', right: 'Actual Meal', category: 'food' },
	{ left: 'Hangover Cure', right: 'Hangover Cause', category: 'food' },
	{ left: 'Childhood Favorite', right: 'Adult Discovery', category: 'food' },
	{ left: 'One Bite Is Enough', right: 'Can Not Stop Eating', category: 'food' },
	{ left: 'Tastes Like Nothing', right: 'Flavor Explosion', category: 'food' },
	{ left: 'Diet Killer', right: 'Diet Friendly', category: 'food' },

	// social
	{ left: 'Introvert Activity', right: 'Extrovert Activity', category: 'social' },
	{ left: 'First Date', right: 'Tenth Date', category: 'social' },
	{ left: 'Awkward', right: 'Smooth', category: 'social' },
	{ left: 'Solo Trip', right: 'Group Trip', category: 'social' },
	{ left: 'Kills Conversation', right: 'Sparks Conversation', category: 'social' },
	{ left: 'Antisocial', right: 'Life of the Party', category: 'social' },
	{ left: 'Red Flag', right: 'Green Flag', category: 'social' },
	{ left: 'Oversharing', right: 'Too Mysterious', category: 'social' },
	{ left: 'Embarrassing in Public', right: 'Impressive in Public', category: 'social' },
	{ left: 'Canceled Invite', right: 'Must Invite', category: 'social' },
	{ left: 'Work Friend Only', right: 'Real Friend', category: 'social' },
	{ left: 'Nervous Habit', right: 'Confident Habit', category: 'social' },
	{ left: 'Too Much Eye Contact', right: 'Too Little Eye Contact', category: 'social' },
	{ left: 'Early Arrival', right: 'Fashionably Late', category: 'social' },
	{ left: 'Text Only', right: 'Call Me Now', category: 'social' },
	{ left: 'Ghost Zone', right: 'Reply Immediately', category: 'social' },
	{ left: 'Inside Joke', right: 'Public Humor', category: 'social' },
	{ left: 'Crowd Drainer', right: 'Energy Giver', category: 'social' },
	{ left: 'Conversation Stopper', right: 'Conversation Starter', category: 'social' },
	{ left: 'Blends Into the Wall', right: 'Center of Attention', category: 'social' },
	{ left: 'Always the Host', right: 'Always the Guest', category: 'social' },
	{ left: 'Remembers Your Birthday', right: 'Forgets Your Name', category: 'social' },
	{ left: 'Shares Too Much', right: 'Shares Nothing', category: 'social' },
	{ left: 'Leaves on Read', right: 'Triple Texts You', category: 'social' },
	{ left: 'Brutally Honest', right: 'Polite Liar', category: 'social' },
	{ left: 'Friend Collector', right: 'Inner Circle Only', category: 'social' },
	{ left: 'Toxic Positivity', right: 'Refreshing Honesty', category: 'social' },
	{ left: 'Says It Online', right: 'Says It to Your Face', category: 'social' },
	{ left: 'Picks the Restaurant', right: 'Says I Dunno', category: 'social' },

	// absurd
	{ left: 'Would Fight', right: 'Would Befriend', category: 'absurd' },
	{ left: 'Apocalypse Useless', right: 'Apocalypse Essential', category: 'absurd' },
	{ left: 'Die First', right: 'Survive Horror Movie', category: 'absurd' },
	{ left: 'Villain Origin Story', right: 'Hero Origin Story', category: 'absurd' },
	{ left: 'Time Travel Disaster', right: 'Time Travel Success', category: 'absurd' },
	{ left: 'Haunted Object', right: 'Lucky Charm', category: 'absurd' },
	{ left: 'Terrible Sidekick', right: 'Perfect Sidekick', category: 'absurd' },
	{ left: 'Betrays the Group', right: 'Sacrifices for Group', category: 'absurd' },
	{ left: 'Gets Eaten First', right: 'Outruns the Monster', category: 'absurd' },
	{ left: 'Loses the Map', right: 'Finds the Exit', category: 'absurd' },
	{ left: 'Wakes the Neighbors', right: 'Sneaks In Silently', category: 'absurd' },
	{ left: 'Robot Would Replace', right: 'Robot Cannot Replace', category: 'absurd' },
	{ left: 'Alien Abduction Risk', right: 'Alien Ambassador', category: 'absurd' },
	{ left: 'Haunted By', right: 'Protected By', category: 'absurd' },
	{ left: 'Wrong Side of History', right: 'Right Side of History', category: 'absurd' },
	{ left: 'Failed Prophecy', right: 'Fulfilled Prophecy', category: 'absurd' },
	{ left: 'Cursed Artifact', right: 'Enchanted Relic', category: 'absurd' },
	{ left: 'Accidental Villain', right: 'Unlikely Hero', category: 'absurd' },
	{ left: 'Brings a Knife', right: 'Brings a Spreadsheet', category: 'absurd' },
	{ left: 'Eaten by Shark', right: 'Befriends the Shark', category: 'absurd' },
	{ left: 'Worst Last Words', right: 'Best Last Words', category: 'absurd' },
	{ left: 'Breaks the Simulation', right: 'Never Notices', category: 'absurd' },
	{ left: 'Dies in the Tutorial', right: 'Speedruns the Game', category: 'absurd' },
	{ left: 'Summons the Demon', right: 'Banishes the Demon', category: 'absurd' },
	{ left: 'Starts the Fire', right: 'Puts Out the Fire', category: 'absurd' },
	{ left: 'Makes It Worse', right: 'Saves the Day', category: 'absurd' },
	{ left: 'Banned in Every Country', right: 'National Treasure', category: 'absurd' },
	{ left: 'Florida Man Activity', right: 'Nobel Prize Activity', category: 'absurd' },
	{ left: 'Trap Card', right: 'Power-Up', category: 'absurd' },

	// friend_group
	{ left: 'Always Late', right: 'Always Early', category: 'friend_group' },
	{ left: 'Group Chat Silent', right: 'Group Chat Spammer', category: 'friend_group' },
	{ left: 'Plans the Trip', right: 'Just Shows Up', category: 'friend_group' },
	{ left: 'Borrows Everything', right: 'Lends Everything', category: 'friend_group' },
	{ left: 'Drama Starter', right: 'Peacemaker', category: 'friend_group' },
	{ left: 'Disappears for Months', right: 'Always Around', category: 'friend_group' },
	{ left: 'Pays Last', right: 'Covers Everyone', category: 'friend_group' },
	{ left: 'Gives Tough Love', right: 'Gives Comfort', category: 'friend_group' },
	{ left: 'Has Tea on Everyone', right: 'Knows Nothing', category: 'friend_group' },
	{ left: 'Hype Friend', right: 'Honest Friend', category: 'friend_group' },
	{ left: 'Holds Grudges', right: 'Forgives Instantly', category: 'friend_group' },
	{ left: 'Friend Since Birth', right: 'Met Last Year', category: 'friend_group' },
	{ left: 'Worst Influence', right: 'Best Influence', category: 'friend_group' },
	{ left: 'Flakes on Plans', right: 'Never Cancels', category: 'friend_group' },
	{ left: 'Secret Keeper', right: 'Tells Everyone', category: 'friend_group' },
	{ left: 'Main Character', right: 'Supporting Cast', category: 'friend_group' },
	{ left: 'Gives Bad Advice', right: 'Gives Great Advice', category: 'friend_group' },
	{ left: 'Over-Communicator', right: 'Under-Communicator', category: 'friend_group' },
	{ left: 'Remembers Every Detail', right: 'Forgets Immediately', category: 'friend_group' },
	{ left: 'Picks the Movie', right: 'Falls Asleep During It', category: 'friend_group' },
	{ left: 'Takes the Photos', right: 'Never in the Photos', category: 'friend_group' },
	{ left: 'Orders for the Table', right: 'Cannot Decide', category: 'friend_group' },
	{ left: 'Emotional Support', right: 'Practical Support', category: 'friend_group' },
	{ left: 'Road Trip DJ', right: 'Road Trip Sleeper', category: 'friend_group' },
	{ left: 'Brings Snacks', right: 'Eats All the Snacks', category: 'friend_group' },
	{ left: 'Says We Should Hang', right: 'Actually Plans It', category: 'friend_group' },
	{ left: 'Knows Everyone', right: 'Only Knows You', category: 'friend_group' },
	{ left: 'Thrives in Crisis', right: 'Panics in Crisis', category: 'friend_group' },
	{ left: 'Moves Away', right: 'Never Leaves Town', category: 'friend_group' },

	// technology
	{ left: 'Already Obsolete', right: 'Ahead of Its Time', category: 'technology' },
	{ left: 'Privacy Nightmare', right: 'Privacy Friendly', category: 'technology' },
	{ left: 'Solves a Real Problem', right: 'Solution Looking for a Problem', category: 'technology' },
	{ left: 'Makes Life Easier', right: 'Makes Life Harder', category: 'technology' },
	{ left: 'Replaces Humans', right: 'Empowers Humans', category: 'technology' },
	{ left: 'All Hype', right: 'Actually Revolutionary', category: 'technology' },
	{ left: 'Early Adopter Only', right: 'Everyone Should Use It', category: 'technology' },
	{ left: 'Better Before the Update', right: 'Better After the Update', category: 'technology' },
	{ left: 'One More Subscription', right: 'Worth the Subscription', category: 'technology' },
	{ left: 'Peak Already Passed', right: 'Best Years Ahead', category: 'technology' },
	{ left: 'Distraction Machine', right: 'Productivity Tool', category: 'technology' },
	{ left: 'Kids Get It', right: 'Only Adults Get It', category: 'technology' },
	{ left: 'Killed Something Better', right: 'Replaced Something Worse', category: 'technology' },
	{ left: 'Will Age Terribly', right: 'Will Age Gracefully', category: 'technology' },
	{ left: 'Cool Demo Only', right: 'Actually Useful Daily', category: 'technology' },
	{ left: 'Open Source Spirit', right: 'Locked-Down Walled Garden', category: 'technology' },
	{ left: 'Hardware Matters More', right: 'Software Matters More', category: 'technology' },
	{ left: 'Fixes Itself', right: 'Breaks Constantly', category: 'technology' },

	// lifestyle
	{ left: 'Morning Person', right: 'Night Owl', category: 'lifestyle' },
	{ left: 'Minimalist', right: 'Maximalist', category: 'lifestyle' },
	{ left: 'City Life', right: 'Country Life', category: 'lifestyle' },
	{ left: 'Routine', right: 'Spontaneous', category: 'lifestyle' },
	{ left: 'Homebody', right: 'Always Out', category: 'lifestyle' },
	{ left: 'Save Every Penny', right: 'Spend It All', category: 'lifestyle' },
	{ left: 'Travel Light', right: 'Pack Everything', category: 'lifestyle' },
	{ left: 'Gym Rat', right: 'Couch Potato', category: 'lifestyle' },
	{ left: 'DIY Everything', right: 'Hire a Professional', category: 'lifestyle' },
	{ left: 'Early Retirement', right: 'Work Forever', category: 'lifestyle' },
	{ left: 'Rent Forever', right: 'Must Own a Home', category: 'lifestyle' },
	{ left: 'Capsule Wardrobe', right: 'Overflowing Closet', category: 'lifestyle' },
	{ left: 'Read the Manual', right: 'Figure It Out', category: 'lifestyle' },
	{ left: 'Meal Prep Sunday', right: 'Order Delivery', category: 'lifestyle' },
	{ left: 'No Screens Before Bed', right: 'Phone in Hand All Night', category: 'lifestyle' },
	{ left: 'Cold Shower', right: 'Scalding Hot Shower', category: 'lifestyle' },
	{ left: 'Five-Year Plan', right: 'Winging It', category: 'lifestyle' },
	{ left: 'One Hobby Deep', right: 'New Hobby Every Week', category: 'lifestyle' },
];

export function getCategories(): string[] {
	return Object.keys(CATEGORY_LABELS);
}

export function shuffleDeck(categories?: string[]): SpectrumCard[] {
	let cards = categories && categories.length > 0
		? deck.filter(c => categories.includes(c.category))
		: [...deck];
	for (let i = cards.length - 1; i > 0; i--) {
		const j = Math.floor(Math.random() * (i + 1));
		[cards[i], cards[j]] = [cards[j], cards[i]];
	}
	return cards;
}

export default deck;
